/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { CloudinaryAssetMgmtError } from "./cloudinaryassetmgmterror.js";

/**
 * Version not found
 */
export type NotFoundErrorData = {
  error?: operations.NotFoundError | undefined;
};

/**
 * Version not found
 */
export class NotFoundError extends CloudinaryAssetMgmtError {
  error?: operations.NotFoundError | undefined;

  /** The original data that was passed to this error instance. */
  data$: NotFoundErrorData;

  constructor(
    err: NotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "NotFoundError";
  }
}

/**
 * Authentication failed
 */
export type DownloadBackupAssetUnauthorizedErrorData = {
  error?: operations.DownloadBackupAssetUnauthorizedError | undefined;
};

/**
 * Authentication failed
 */
export class DownloadBackupAssetUnauthorizedError
  extends CloudinaryAssetMgmtError
{
  error?: operations.DownloadBackupAssetUnauthorizedError | undefined;

  /** The original data that was passed to this error instance. */
  data$: DownloadBackupAssetUnauthorizedErrorData;

  constructor(
    err: DownloadBackupAssetUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "DownloadBackupAssetUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type BadRequestErrorData = {
  error?: operations.BadRequestError | undefined;
};

/**
 * Bad request
 */
export class BadRequestError extends CloudinaryAssetMgmtError {
  error?: operations.BadRequestError | undefined;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "BadRequestError";
  }
}

/** @internal */
export const NotFoundError$inboundSchema: z.ZodType<
  NotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.NotFoundError$inboundSchema).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new NotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type NotFoundError$Outbound = {
  error?: operations.NotFoundError$Outbound | undefined;
};

/** @internal */
export const NotFoundError$outboundSchema: z.ZodType<
  NotFoundError$Outbound,
  z.ZodTypeDef,
  NotFoundError
> = z.instanceof(NotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.NotFoundError$outboundSchema).optional(),
  }));

/** @internal */
export const DownloadBackupAssetUnauthorizedError$inboundSchema: z.ZodType<
  DownloadBackupAssetUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() =>
    operations.DownloadBackupAssetUnauthorizedError$inboundSchema
  ).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DownloadBackupAssetUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DownloadBackupAssetUnauthorizedError$Outbound = {
  error?: operations.DownloadBackupAssetUnauthorizedError$Outbound | undefined;
};

/** @internal */
export const DownloadBackupAssetUnauthorizedError$outboundSchema: z.ZodType<
  DownloadBackupAssetUnauthorizedError$Outbound,
  z.ZodTypeDef,
  DownloadBackupAssetUnauthorizedError
> = z.instanceof(DownloadBackupAssetUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() =>
      operations.DownloadBackupAssetUnauthorizedError$outboundSchema
    ).optional(),
  }));

/** @internal */
export const BadRequestError$inboundSchema: z.ZodType<
  BadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => operations.BadRequestError$inboundSchema).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new BadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type BadRequestError$Outbound = {
  error?: operations.BadRequestError$Outbound | undefined;
};

/** @internal */
export const BadRequestError$outboundSchema: z.ZodType<
  BadRequestError$Outbound,
  z.ZodTypeDef,
  BadRequestError
> = z.instanceof(BadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.lazy(() => operations.BadRequestError$outboundSchema).optional(),
  }));
