/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestroyAssetGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type DestroyAssetRequest = {
  /**
   * The type of resource.
   */
  resourceType: components.ResourceType;
  /**
   * The public ID of the asset.
   */
  publicId: string;
  /**
   * Whether to invalidate CDN cached copies of the asset
   */
  invalidate?: boolean | undefined;
};

/**
 * Result of the deletion operation
 */
export const Result = {
  Ok: "ok",
  NotFound: "not found",
} as const;
/**
 * Result of the deletion operation
 */
export type Result = ClosedEnum<typeof Result>;

/**
 * Asset/resource destroyed successfully or not found
 */
export type DestroyAssetResponse = {
  /**
   * Result of the deletion operation
   */
  result?: Result | undefined;
};

/** @internal */
export const DestroyAssetGlobals$inboundSchema: z.ZodType<
  DestroyAssetGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type DestroyAssetGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const DestroyAssetGlobals$outboundSchema: z.ZodType<
  DestroyAssetGlobals$Outbound,
  z.ZodTypeDef,
  DestroyAssetGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function destroyAssetGlobalsToJSON(
  destroyAssetGlobals: DestroyAssetGlobals,
): string {
  return JSON.stringify(
    DestroyAssetGlobals$outboundSchema.parse(destroyAssetGlobals),
  );
}
export function destroyAssetGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DestroyAssetGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyAssetGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyAssetGlobals' from JSON`,
  );
}

/** @internal */
export const DestroyAssetRequest$inboundSchema: z.ZodType<
  DestroyAssetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: components.ResourceType$inboundSchema,
  public_id: z.string(),
  invalidate: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "public_id": "publicId",
  });
});
/** @internal */
export type DestroyAssetRequest$Outbound = {
  resource_type: string;
  public_id: string;
  invalidate: boolean;
};

/** @internal */
export const DestroyAssetRequest$outboundSchema: z.ZodType<
  DestroyAssetRequest$Outbound,
  z.ZodTypeDef,
  DestroyAssetRequest
> = z.object({
  resourceType: components.ResourceType$outboundSchema,
  publicId: z.string(),
  invalidate: z.boolean().default(false),
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    publicId: "public_id",
  });
});

export function destroyAssetRequestToJSON(
  destroyAssetRequest: DestroyAssetRequest,
): string {
  return JSON.stringify(
    DestroyAssetRequest$outboundSchema.parse(destroyAssetRequest),
  );
}
export function destroyAssetRequestFromJSON(
  jsonString: string,
): SafeParseResult<DestroyAssetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyAssetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyAssetRequest' from JSON`,
  );
}

/** @internal */
export const Result$inboundSchema: z.ZodNativeEnum<typeof Result> = z
  .nativeEnum(Result);
/** @internal */
export const Result$outboundSchema: z.ZodNativeEnum<typeof Result> =
  Result$inboundSchema;

/** @internal */
export const DestroyAssetResponse$inboundSchema: z.ZodType<
  DestroyAssetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  result: Result$inboundSchema.optional(),
});
/** @internal */
export type DestroyAssetResponse$Outbound = {
  result?: string | undefined;
};

/** @internal */
export const DestroyAssetResponse$outboundSchema: z.ZodType<
  DestroyAssetResponse$Outbound,
  z.ZodTypeDef,
  DestroyAssetResponse
> = z.object({
  result: Result$outboundSchema.optional(),
});

export function destroyAssetResponseToJSON(
  destroyAssetResponse: DestroyAssetResponse,
): string {
  return JSON.stringify(
    DestroyAssetResponse$outboundSchema.parse(destroyAssetResponse),
  );
}
export function destroyAssetResponseFromJSON(
  jsonString: string,
): SafeParseResult<DestroyAssetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyAssetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyAssetResponse' from JSON`,
  );
}
