/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DestroyFolderGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type DestroyFolderRequest = {
  folder: string;
};

/**
 * Folder deleted successfully
 */
export type DestroyFolderResponse = {
  /**
   * List of deleted folder paths
   */
  deleted: Array<string>;
};

/** @internal */
export const DestroyFolderGlobals$inboundSchema: z.ZodType<
  DestroyFolderGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type DestroyFolderGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const DestroyFolderGlobals$outboundSchema: z.ZodType<
  DestroyFolderGlobals$Outbound,
  z.ZodTypeDef,
  DestroyFolderGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function destroyFolderGlobalsToJSON(
  destroyFolderGlobals: DestroyFolderGlobals,
): string {
  return JSON.stringify(
    DestroyFolderGlobals$outboundSchema.parse(destroyFolderGlobals),
  );
}
export function destroyFolderGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DestroyFolderGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyFolderGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyFolderGlobals' from JSON`,
  );
}

/** @internal */
export const DestroyFolderRequest$inboundSchema: z.ZodType<
  DestroyFolderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  folder: z.string(),
});
/** @internal */
export type DestroyFolderRequest$Outbound = {
  folder: string;
};

/** @internal */
export const DestroyFolderRequest$outboundSchema: z.ZodType<
  DestroyFolderRequest$Outbound,
  z.ZodTypeDef,
  DestroyFolderRequest
> = z.object({
  folder: z.string(),
});

export function destroyFolderRequestToJSON(
  destroyFolderRequest: DestroyFolderRequest,
): string {
  return JSON.stringify(
    DestroyFolderRequest$outboundSchema.parse(destroyFolderRequest),
  );
}
export function destroyFolderRequestFromJSON(
  jsonString: string,
): SafeParseResult<DestroyFolderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyFolderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyFolderRequest' from JSON`,
  );
}

/** @internal */
export const DestroyFolderResponse$inboundSchema: z.ZodType<
  DestroyFolderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  deleted: z.array(z.string()),
});
/** @internal */
export type DestroyFolderResponse$Outbound = {
  deleted: Array<string>;
};

/** @internal */
export const DestroyFolderResponse$outboundSchema: z.ZodType<
  DestroyFolderResponse$Outbound,
  z.ZodTypeDef,
  DestroyFolderResponse
> = z.object({
  deleted: z.array(z.string()),
});

export function destroyFolderResponseToJSON(
  destroyFolderResponse: DestroyFolderResponse,
): string {
  return JSON.stringify(
    DestroyFolderResponse$outboundSchema.parse(destroyFolderResponse),
  );
}
export function destroyFolderResponseFromJSON(
  jsonString: string,
): SafeParseResult<DestroyFolderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DestroyFolderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DestroyFolderResponse' from JSON`,
  );
}
