/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TextGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

/**
 * The type of resource to create. Must be "image" for text generation.
 */
export const TextResourceType = {
  Image: "image",
} as const;
/**
 * The type of resource to create. Must be "image" for text generation.
 */
export type TextResourceType = ClosedEnum<typeof TextResourceType>;

/**
 * Text alignment (left, center, right, justify).
 */
export const TextAlign = {
  Left: "left",
  Center: "center",
  Right: "right",
  Justify: "justify",
} as const;
/**
 * Text alignment (left, center, right, justify).
 */
export type TextAlign = ClosedEnum<typeof TextAlign>;

/**
 * Whether to use a normal or bold font.
 */
export const FontWeight = {
  Normal: "normal",
  Bold: "bold",
} as const;
/**
 * Whether to use a normal or bold font.
 */
export type FontWeight = ClosedEnum<typeof FontWeight>;

/**
 * Whether to use a normal or italic font.
 */
export const FontStyle = {
  Normal: "normal",
  Italic: "italic",
} as const;
/**
 * Whether to use a normal or italic font.
 */
export type FontStyle = ClosedEnum<typeof FontStyle>;

/**
 * Text decoration style.
 */
export const TextDecoration = {
  None: "none",
  Underline: "underline",
} as const;
/**
 * Text decoration style.
 */
export type TextDecoration = ClosedEnum<typeof TextDecoration>;

export type TextRequestBody = {
  /**
   * The text string to generate an image for.
   */
  text: string;
  /**
   * The identifier that is used for accessing the generated image. If not specified, a unique identifier is generated.
   */
  publicId?: string | undefined;
  /**
   * The name of the font family.
   */
  fontFamily?: string | undefined;
  /**
   * Font size in points.
   */
  fontSize?: number | undefined;
  /**
   * Name or RGB representation of the font's color (e.g., red or
   */
  fontColor?: string | undefined;
  /**
   * Text alignment (left, center, right, justify).
   */
  textAlign?: TextAlign | undefined;
  /**
   * Whether to use a normal or bold font.
   */
  fontWeight?: FontWeight | undefined;
  /**
   * Whether to use a normal or italic font.
   */
  fontStyle?: FontStyle | undefined;
  /**
   * Name or RGB representation of the background color (e.g., red or
   */
  background?: string | undefined;
  /**
   * Text opacity value between 0 (invisible) and 100.
   */
  opacity?: number | undefined;
  /**
   * Text decoration style.
   */
  textDecoration?: TextDecoration | undefined;
  /**
   * The spacing between lines of text in pixels.
   */
  lineSpacing?: number | undefined;
};

export type TextRequest = {
  /**
   * The type of resource to create. Must be "image" for text generation.
   */
  resourceType: TextResourceType;
  requestBody: TextRequestBody;
};

export type Region = {};

/**
 * Moderation information for the asset.
 */
export type Moderation = {};

/**
 * Additional information about the asset.
 */
export type Info = {};

/**
 * Text image created successfully
 */
export type TextResponse = {
  /**
   * The unique identifier of the asset.
   */
  assetId?: string | undefined;
  /**
   * The public identifier of the asset.
   */
  publicId?: string | undefined;
  /**
   * The version number of the asset.
   */
  version?: number | undefined;
  /**
   * The version identifier of the asset.
   */
  versionId?: string | undefined;
  /**
   * The signature for the asset.
   */
  signature?: string | undefined;
  /**
   * The width of the generated image in pixels.
   */
  width?: number | undefined;
  /**
   * The height of the generated image in pixels.
   */
  height?: number | undefined;
  /**
   * The format of the generated image.
   */
  format?: string | undefined;
  /**
   * The type of resource (image).
   */
  resourceType?: string | undefined;
  /**
   * The creation timestamp.
   */
  createdAt?: Date | undefined;
  /**
   * Array of tags assigned to the asset.
   */
  tags?: Array<string> | undefined;
  /**
   * Number of pages in the asset.
   */
  pages?: number | undefined;
  /**
   * Size of the asset in bytes.
   */
  bytes?: number | undefined;
  /**
   * The storage type of the asset.
   */
  type?: string | undefined;
  /**
   * The ETag of the asset.
   */
  etag?: string | undefined;
  /**
   * Whether the asset is a placeholder.
   */
  placeholder?: boolean | undefined;
  /**
   * The HTTP URL for accessing the asset.
   */
  url?: string | undefined;
  /**
   * The HTTPS URL for accessing the asset.
   */
  secureUrl?: string | undefined;
  /**
   * The display name of the asset.
   */
  displayName?: string | undefined;
  /**
   * The access mode of the asset.
   */
  accessMode?: string | undefined;
  /**
   * Restricts access to the asset by specifying one or more access types.
   *
   * @remarks
   * The asset is restricted unless at least one listed access type is valid.
   */
  accessControl?: Array<components.AccessControlItem> | undefined;
  /**
   * Region information for the asset.
   */
  regions?: Array<Region> | undefined;
  /**
   * Moderation information for the asset.
   */
  moderation?: Moderation | undefined;
  /**
   * Additional information about the asset.
   */
  info?: Info | undefined;
};

/** @internal */
export const TextGlobals$inboundSchema: z.ZodType<
  TextGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type TextGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const TextGlobals$outboundSchema: z.ZodType<
  TextGlobals$Outbound,
  z.ZodTypeDef,
  TextGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function textGlobalsToJSON(textGlobals: TextGlobals): string {
  return JSON.stringify(TextGlobals$outboundSchema.parse(textGlobals));
}
export function textGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<TextGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextGlobals' from JSON`,
  );
}

/** @internal */
export const TextResourceType$inboundSchema: z.ZodNativeEnum<
  typeof TextResourceType
> = z.nativeEnum(TextResourceType);
/** @internal */
export const TextResourceType$outboundSchema: z.ZodNativeEnum<
  typeof TextResourceType
> = TextResourceType$inboundSchema;

/** @internal */
export const TextAlign$inboundSchema: z.ZodNativeEnum<typeof TextAlign> = z
  .nativeEnum(TextAlign);
/** @internal */
export const TextAlign$outboundSchema: z.ZodNativeEnum<typeof TextAlign> =
  TextAlign$inboundSchema;

/** @internal */
export const FontWeight$inboundSchema: z.ZodNativeEnum<typeof FontWeight> = z
  .nativeEnum(FontWeight);
/** @internal */
export const FontWeight$outboundSchema: z.ZodNativeEnum<typeof FontWeight> =
  FontWeight$inboundSchema;

/** @internal */
export const FontStyle$inboundSchema: z.ZodNativeEnum<typeof FontStyle> = z
  .nativeEnum(FontStyle);
/** @internal */
export const FontStyle$outboundSchema: z.ZodNativeEnum<typeof FontStyle> =
  FontStyle$inboundSchema;

/** @internal */
export const TextDecoration$inboundSchema: z.ZodNativeEnum<
  typeof TextDecoration
> = z.nativeEnum(TextDecoration);
/** @internal */
export const TextDecoration$outboundSchema: z.ZodNativeEnum<
  typeof TextDecoration
> = TextDecoration$inboundSchema;

/** @internal */
export const TextRequestBody$inboundSchema: z.ZodType<
  TextRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  public_id: z.string().optional(),
  font_family: z.string().optional(),
  font_size: z.number().int().default(12),
  font_color: z.string().default("black"),
  text_align: TextAlign$inboundSchema.optional(),
  font_weight: FontWeight$inboundSchema.default("normal"),
  font_style: FontStyle$inboundSchema.default("normal"),
  background: z.string().default("transparent"),
  opacity: z.number().int().default(100),
  text_decoration: TextDecoration$inboundSchema.default("none"),
  line_spacing: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "public_id": "publicId",
    "font_family": "fontFamily",
    "font_size": "fontSize",
    "font_color": "fontColor",
    "text_align": "textAlign",
    "font_weight": "fontWeight",
    "font_style": "fontStyle",
    "text_decoration": "textDecoration",
    "line_spacing": "lineSpacing",
  });
});
/** @internal */
export type TextRequestBody$Outbound = {
  text: string;
  public_id?: string | undefined;
  font_family?: string | undefined;
  font_size: number;
  font_color: string;
  text_align?: string | undefined;
  font_weight: string;
  font_style: string;
  background: string;
  opacity: number;
  text_decoration: string;
  line_spacing?: number | undefined;
};

/** @internal */
export const TextRequestBody$outboundSchema: z.ZodType<
  TextRequestBody$Outbound,
  z.ZodTypeDef,
  TextRequestBody
> = z.object({
  text: z.string(),
  publicId: z.string().optional(),
  fontFamily: z.string().optional(),
  fontSize: z.number().int().default(12),
  fontColor: z.string().default("black"),
  textAlign: TextAlign$outboundSchema.optional(),
  fontWeight: FontWeight$outboundSchema.default("normal"),
  fontStyle: FontStyle$outboundSchema.default("normal"),
  background: z.string().default("transparent"),
  opacity: z.number().int().default(100),
  textDecoration: TextDecoration$outboundSchema.default("none"),
  lineSpacing: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    publicId: "public_id",
    fontFamily: "font_family",
    fontSize: "font_size",
    fontColor: "font_color",
    textAlign: "text_align",
    fontWeight: "font_weight",
    fontStyle: "font_style",
    textDecoration: "text_decoration",
    lineSpacing: "line_spacing",
  });
});

export function textRequestBodyToJSON(
  textRequestBody: TextRequestBody,
): string {
  return JSON.stringify(TextRequestBody$outboundSchema.parse(textRequestBody));
}
export function textRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<TextRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextRequestBody' from JSON`,
  );
}

/** @internal */
export const TextRequest$inboundSchema: z.ZodType<
  TextRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  resource_type: TextResourceType$inboundSchema,
  RequestBody: z.lazy(() => TextRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "resource_type": "resourceType",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type TextRequest$Outbound = {
  resource_type: string;
  RequestBody: TextRequestBody$Outbound;
};

/** @internal */
export const TextRequest$outboundSchema: z.ZodType<
  TextRequest$Outbound,
  z.ZodTypeDef,
  TextRequest
> = z.object({
  resourceType: TextResourceType$outboundSchema,
  requestBody: z.lazy(() => TextRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    resourceType: "resource_type",
    requestBody: "RequestBody",
  });
});

export function textRequestToJSON(textRequest: TextRequest): string {
  return JSON.stringify(TextRequest$outboundSchema.parse(textRequest));
}
export function textRequestFromJSON(
  jsonString: string,
): SafeParseResult<TextRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextRequest' from JSON`,
  );
}

/** @internal */
export const Region$inboundSchema: z.ZodType<Region, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Region$Outbound = {};

/** @internal */
export const Region$outboundSchema: z.ZodType<
  Region$Outbound,
  z.ZodTypeDef,
  Region
> = z.object({});

export function regionToJSON(region: Region): string {
  return JSON.stringify(Region$outboundSchema.parse(region));
}
export function regionFromJSON(
  jsonString: string,
): SafeParseResult<Region, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Region$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Region' from JSON`,
  );
}

/** @internal */
export const Moderation$inboundSchema: z.ZodType<
  Moderation,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type Moderation$Outbound = {};

/** @internal */
export const Moderation$outboundSchema: z.ZodType<
  Moderation$Outbound,
  z.ZodTypeDef,
  Moderation
> = z.object({});

export function moderationToJSON(moderation: Moderation): string {
  return JSON.stringify(Moderation$outboundSchema.parse(moderation));
}
export function moderationFromJSON(
  jsonString: string,
): SafeParseResult<Moderation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Moderation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Moderation' from JSON`,
  );
}

/** @internal */
export const Info$inboundSchema: z.ZodType<Info, z.ZodTypeDef, unknown> = z
  .object({});
/** @internal */
export type Info$Outbound = {};

/** @internal */
export const Info$outboundSchema: z.ZodType<Info$Outbound, z.ZodTypeDef, Info> =
  z.object({});

export function infoToJSON(info: Info): string {
  return JSON.stringify(Info$outboundSchema.parse(info));
}
export function infoFromJSON(
  jsonString: string,
): SafeParseResult<Info, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Info$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Info' from JSON`,
  );
}

/** @internal */
export const TextResponse$inboundSchema: z.ZodType<
  TextResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  asset_id: z.string().optional(),
  public_id: z.string().optional(),
  version: z.number().int().optional(),
  version_id: z.string().optional(),
  signature: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  format: z.string().optional(),
  resource_type: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  tags: z.array(z.string()).optional(),
  pages: z.number().int().optional(),
  bytes: z.number().int().optional(),
  type: z.string().optional(),
  etag: z.string().optional(),
  placeholder: z.boolean().optional(),
  url: z.string().optional(),
  secure_url: z.string().optional(),
  display_name: z.string().optional(),
  access_mode: z.string().optional(),
  access_control: z.array(components.AccessControlItem$inboundSchema)
    .optional(),
  regions: z.array(z.lazy(() => Region$inboundSchema)).optional(),
  moderation: z.lazy(() => Moderation$inboundSchema).optional(),
  info: z.lazy(() => Info$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "asset_id": "assetId",
    "public_id": "publicId",
    "version_id": "versionId",
    "resource_type": "resourceType",
    "created_at": "createdAt",
    "secure_url": "secureUrl",
    "display_name": "displayName",
    "access_mode": "accessMode",
    "access_control": "accessControl",
  });
});
/** @internal */
export type TextResponse$Outbound = {
  asset_id?: string | undefined;
  public_id?: string | undefined;
  version?: number | undefined;
  version_id?: string | undefined;
  signature?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  format?: string | undefined;
  resource_type?: string | undefined;
  created_at?: string | undefined;
  tags?: Array<string> | undefined;
  pages?: number | undefined;
  bytes?: number | undefined;
  type?: string | undefined;
  etag?: string | undefined;
  placeholder?: boolean | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  display_name?: string | undefined;
  access_mode?: string | undefined;
  access_control?: Array<components.AccessControlItem$Outbound> | undefined;
  regions?: Array<Region$Outbound> | undefined;
  moderation?: Moderation$Outbound | undefined;
  info?: Info$Outbound | undefined;
};

/** @internal */
export const TextResponse$outboundSchema: z.ZodType<
  TextResponse$Outbound,
  z.ZodTypeDef,
  TextResponse
> = z.object({
  assetId: z.string().optional(),
  publicId: z.string().optional(),
  version: z.number().int().optional(),
  versionId: z.string().optional(),
  signature: z.string().optional(),
  width: z.number().int().optional(),
  height: z.number().int().optional(),
  format: z.string().optional(),
  resourceType: z.string().optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  tags: z.array(z.string()).optional(),
  pages: z.number().int().optional(),
  bytes: z.number().int().optional(),
  type: z.string().optional(),
  etag: z.string().optional(),
  placeholder: z.boolean().optional(),
  url: z.string().optional(),
  secureUrl: z.string().optional(),
  displayName: z.string().optional(),
  accessMode: z.string().optional(),
  accessControl: z.array(components.AccessControlItem$outboundSchema)
    .optional(),
  regions: z.array(z.lazy(() => Region$outboundSchema)).optional(),
  moderation: z.lazy(() => Moderation$outboundSchema).optional(),
  info: z.lazy(() => Info$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    assetId: "asset_id",
    publicId: "public_id",
    versionId: "version_id",
    resourceType: "resource_type",
    createdAt: "created_at",
    secureUrl: "secure_url",
    displayName: "display_name",
    accessMode: "access_mode",
    accessControl: "access_control",
  });
});

export function textResponseToJSON(textResponse: TextResponse): string {
  return JSON.stringify(TextResponse$outboundSchema.parse(textResponse));
}
export function textResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextResponse' from JSON`,
  );
}
