/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePersonGlobals = {
  /**
   * The cloud name of your product environment.
   */
  cloudName?: string | undefined;
};

export type UpdatePersonRequestBody = {
  /**
   * The display name for the person. Maximum 255 characters.
   */
  name?: string | undefined;
  /**
   * The status of a person.
   */
  status?: components.PersonStatus | undefined;
  /**
   * The external ID of an asset containing this person's face to use as the thumbnail.
   */
  thumbnailAssetId?: string | undefined;
};

export type UpdatePersonRequest = {
  /**
   * The unique identifier of the person.
   */
  personId: string;
  requestBody: UpdatePersonRequestBody;
};

/**
 * Person updated successfully
 */
export type UpdatePersonResponse = {
  /**
   * The unique identifier of the person.
   */
  personId?: string | undefined;
  /**
   * The display name of the person.
   */
  name?: string | undefined;
  /**
   * The status of a person.
   */
  status?: components.PersonStatus | undefined;
};

/** @internal */
export const UpdatePersonGlobals$inboundSchema: z.ZodType<
  UpdatePersonGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});
/** @internal */
export type UpdatePersonGlobals$Outbound = {
  cloud_name?: string | undefined;
};

/** @internal */
export const UpdatePersonGlobals$outboundSchema: z.ZodType<
  UpdatePersonGlobals$Outbound,
  z.ZodTypeDef,
  UpdatePersonGlobals
> = z.object({
  cloudName: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
  });
});

export function updatePersonGlobalsToJSON(
  updatePersonGlobals: UpdatePersonGlobals,
): string {
  return JSON.stringify(
    UpdatePersonGlobals$outboundSchema.parse(updatePersonGlobals),
  );
}
export function updatePersonGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePersonGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePersonGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePersonGlobals' from JSON`,
  );
}

/** @internal */
export const UpdatePersonRequestBody$inboundSchema: z.ZodType<
  UpdatePersonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  status: components.PersonStatus$inboundSchema.optional(),
  thumbnail_asset_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "thumbnail_asset_id": "thumbnailAssetId",
  });
});
/** @internal */
export type UpdatePersonRequestBody$Outbound = {
  name?: string | undefined;
  status?: string | undefined;
  thumbnail_asset_id?: string | undefined;
};

/** @internal */
export const UpdatePersonRequestBody$outboundSchema: z.ZodType<
  UpdatePersonRequestBody$Outbound,
  z.ZodTypeDef,
  UpdatePersonRequestBody
> = z.object({
  name: z.string().optional(),
  status: components.PersonStatus$outboundSchema.optional(),
  thumbnailAssetId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    thumbnailAssetId: "thumbnail_asset_id",
  });
});

export function updatePersonRequestBodyToJSON(
  updatePersonRequestBody: UpdatePersonRequestBody,
): string {
  return JSON.stringify(
    UpdatePersonRequestBody$outboundSchema.parse(updatePersonRequestBody),
  );
}
export function updatePersonRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePersonRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePersonRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePersonRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdatePersonRequest$inboundSchema: z.ZodType<
  UpdatePersonRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  person_id: z.string(),
  RequestBody: z.lazy(() => UpdatePersonRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "person_id": "personId",
    "RequestBody": "requestBody",
  });
});
/** @internal */
export type UpdatePersonRequest$Outbound = {
  person_id: string;
  RequestBody: UpdatePersonRequestBody$Outbound;
};

/** @internal */
export const UpdatePersonRequest$outboundSchema: z.ZodType<
  UpdatePersonRequest$Outbound,
  z.ZodTypeDef,
  UpdatePersonRequest
> = z.object({
  personId: z.string(),
  requestBody: z.lazy(() => UpdatePersonRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    personId: "person_id",
    requestBody: "RequestBody",
  });
});

export function updatePersonRequestToJSON(
  updatePersonRequest: UpdatePersonRequest,
): string {
  return JSON.stringify(
    UpdatePersonRequest$outboundSchema.parse(updatePersonRequest),
  );
}
export function updatePersonRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePersonRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePersonRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePersonRequest' from JSON`,
  );
}

/** @internal */
export const UpdatePersonResponse$inboundSchema: z.ZodType<
  UpdatePersonResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  person_id: z.string().optional(),
  name: z.string().optional(),
  status: components.PersonStatus$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "person_id": "personId",
  });
});
/** @internal */
export type UpdatePersonResponse$Outbound = {
  person_id?: string | undefined;
  name?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdatePersonResponse$outboundSchema: z.ZodType<
  UpdatePersonResponse$Outbound,
  z.ZodTypeDef,
  UpdatePersonResponse
> = z.object({
  personId: z.string().optional(),
  name: z.string().optional(),
  status: components.PersonStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    personId: "person_id",
  });
});

export function updatePersonResponseToJSON(
  updatePersonResponse: UpdatePersonResponse,
): string {
  return JSON.stringify(
    UpdatePersonResponse$outboundSchema.parse(updatePersonResponse),
  );
}
export function updatePersonResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePersonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePersonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePersonResponse' from JSON`,
  );
}
