/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type of access control to apply to the asset.
 */
export const AccessType = {
  Token: "token",
  Anonymous: "anonymous",
} as const;
/**
 * The type of access control to apply to the asset.
 */
export type AccessType = ClosedEnum<typeof AccessType>;

/**
 * Access control rule that defines when and how the asset can be accessed.
 */
export type AccessControlItem = {
  /**
   * The type of access control to apply to the asset.
   */
  accessType: AccessType;
  /**
   * The authentication key identifier for token-based access. Default key is used if not specified or if set to 'default'.
   */
  key?: string | undefined;
  /**
   * The start date and time when anonymous access becomes available (ISO 8601 format).
   */
  start?: string | undefined;
  /**
   * The end date and time when anonymous access expires (ISO 8601 format).
   */
  end?: string | undefined;
};

/** @internal */
export const AccessType$inboundSchema: z.ZodNativeEnum<typeof AccessType> = z
  .nativeEnum(AccessType);
/** @internal */
export const AccessType$outboundSchema: z.ZodNativeEnum<typeof AccessType> =
  AccessType$inboundSchema;

/** @internal */
export const AccessControlItem$inboundSchema: z.ZodType<
  AccessControlItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_type: AccessType$inboundSchema,
  key: z.string().optional(),
  start: z.string().optional(),
  end: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "access_type": "accessType",
  });
});
/** @internal */
export type AccessControlItem$Outbound = {
  access_type: string;
  key?: string | undefined;
  start?: string | undefined;
  end?: string | undefined;
};

/** @internal */
export const AccessControlItem$outboundSchema: z.ZodType<
  AccessControlItem$Outbound,
  z.ZodTypeDef,
  AccessControlItem
> = z.object({
  accessType: AccessType$outboundSchema,
  key: z.string().optional(),
  start: z.string().optional(),
  end: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accessType: "access_type",
  });
});

export function accessControlItemToJSON(
  accessControlItem: AccessControlItem,
): string {
  return JSON.stringify(
    AccessControlItem$outboundSchema.parse(accessControlItem),
  );
}
export function accessControlItemFromJSON(
  jsonString: string,
): SafeParseResult<AccessControlItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessControlItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessControlItem' from JSON`,
  );
}
