/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The storage type of resources to include in the archive.
 */
export const ArchiveStorageType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Fetch: "fetch",
} as const;
/**
 * The storage type of resources to include in the archive.
 */
export type ArchiveStorageType = ClosedEnum<typeof ArchiveStorageType>;

/** @internal */
export const ArchiveStorageType$inboundSchema: z.ZodNativeEnum<
  typeof ArchiveStorageType
> = z.nativeEnum(ArchiveStorageType);
/** @internal */
export const ArchiveStorageType$outboundSchema: z.ZodNativeEnum<
  typeof ArchiveStorageType
> = ArchiveStorageType$inboundSchema;
