/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The extended storage type of the resource.
 */
export const ExtendedStorageType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Fetch: "fetch",
  List: "list",
  Facebook: "facebook",
  Twitter: "twitter",
  Gravatar: "gravatar",
  Youtube: "youtube",
  Hulu: "hulu",
  Vimeo: "vimeo",
  Animoto: "animoto",
  Worldstarhiphop: "worldstarhiphop",
  Dailymotion: "dailymotion",
} as const;
/**
 * The extended storage type of the resource.
 */
export type ExtendedStorageType = ClosedEnum<typeof ExtendedStorageType>;

/** @internal */
export const ExtendedStorageType$inboundSchema: z.ZodNativeEnum<
  typeof ExtendedStorageType
> = z.nativeEnum(ExtendedStorageType);
/** @internal */
export const ExtendedStorageType$outboundSchema: z.ZodNativeEnum<
  typeof ExtendedStorageType
> = ExtendedStorageType$inboundSchema;
