/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccessControlItem,
  AccessControlItem$inboundSchema,
  AccessControlItem$Outbound,
  AccessControlItem$outboundSchema,
} from "./accesscontrolitem.js";

export type InfoContext2 = {
  key?: string | undefined;
  value?: string | undefined;
};

export type InfoContext1 = {
  custom?: { [k: string]: any } | undefined;
};

/**
 * Included if 'context=true' parameter is used. Can be object with custom properties or array of key-value pairs.
 */
export type Context = InfoContext1 | Array<InfoContext2>;

export type Moderation = {
  kind?: string | undefined;
  status?: string | undefined;
  updatedAt?: Date | undefined;
};

export type RelatedAsset = {};

export type Derivative = {
  /**
   * The unique identifier of the derived resource
   */
  id?: string | undefined;
  /**
   * The transformation string that was applied
   */
  transformation?: string | undefined;
  /**
   * The unique signature of the transformation
   */
  transformationSignature?: string | undefined;
  /**
   * The secure URL for accessing the derived resource
   */
  secureUrl?: string | undefined;
};

export type Info = {
  assetId?: string | undefined;
  publicId?: string | undefined;
  assetFolder?: string | undefined;
  displayName?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resourceType?: string | undefined;
  type?: string | undefined;
  createdAt?: Date | undefined;
  uploadedAt?: Date | undefined;
  bytes?: number | undefined;
  backupBytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspectRatio?: number | null | undefined;
  pixels?: number | null | undefined;
  /**
   * Included if 'tags=true' parameter is used.
   */
  tags?: Array<string> | null | undefined;
  /**
   * Included if 'context=true' parameter is used. Can be object with custom properties or array of key-value pairs.
   */
  context?: InfoContext1 | Array<InfoContext2> | null | undefined;
  metadata?: { [k: string]: any } | undefined;
  /**
   * The type of moderation applied to the asset.
   */
  moderationKind?: string | undefined;
  /**
   * The current status of the moderation process for the asset.
   */
  moderationStatus?: string | undefined;
  /**
   * Included if 'moderations=true' parameter is used.
   */
  moderation?: Array<Moderation> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secureUrl?: string | undefined;
  status?: string | undefined;
  accessControl?: Array<AccessControlItem> | null | undefined;
  etag?: string | undefined;
  /**
   * Whether the asset is animated (e.g., GIF, animated WebP). Null for non-animated assets.
   */
  animated?: boolean | null | undefined;
  /**
   * Duration in seconds for video/audio assets. Null for images.
   */
  duration?: number | null | undefined;
  /**
   * The subtype of the resource (e.g., for video). Null when not applicable.
   */
  resourceSubtype?: string | null | undefined;
  /**
   * The substatus of the resource. Null when not set.
   */
  substatus?: string | null | undefined;
  /**
   * Related assets linked to this resource. Null when none linked.
   */
  relatedAssets?: Array<RelatedAsset> | null | undefined;
  /**
   * Included if 'derived=true' parameter is used. Null when no derivatives exist.
   */
  derivatives?: Array<Derivative> | null | undefined;
};

/** @internal */
export const InfoContext2$inboundSchema: z.ZodType<
  InfoContext2,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string().optional(),
  value: z.string().optional(),
});
/** @internal */
export type InfoContext2$Outbound = {
  key?: string | undefined;
  value?: string | undefined;
};

/** @internal */
export const InfoContext2$outboundSchema: z.ZodType<
  InfoContext2$Outbound,
  z.ZodTypeDef,
  InfoContext2
> = z.object({
  key: z.string().optional(),
  value: z.string().optional(),
});

export function infoContext2ToJSON(infoContext2: InfoContext2): string {
  return JSON.stringify(InfoContext2$outboundSchema.parse(infoContext2));
}
export function infoContext2FromJSON(
  jsonString: string,
): SafeParseResult<InfoContext2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoContext2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoContext2' from JSON`,
  );
}

/** @internal */
export const InfoContext1$inboundSchema: z.ZodType<
  InfoContext1,
  z.ZodTypeDef,
  unknown
> = z.object({
  custom: z.record(z.any()).optional(),
});
/** @internal */
export type InfoContext1$Outbound = {
  custom?: { [k: string]: any } | undefined;
};

/** @internal */
export const InfoContext1$outboundSchema: z.ZodType<
  InfoContext1$Outbound,
  z.ZodTypeDef,
  InfoContext1
> = z.object({
  custom: z.record(z.any()).optional(),
});

export function infoContext1ToJSON(infoContext1: InfoContext1): string {
  return JSON.stringify(InfoContext1$outboundSchema.parse(infoContext1));
}
export function infoContext1FromJSON(
  jsonString: string,
): SafeParseResult<InfoContext1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InfoContext1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InfoContext1' from JSON`,
  );
}

/** @internal */
export const Context$inboundSchema: z.ZodType<Context, z.ZodTypeDef, unknown> =
  z.union([
    z.lazy(() => InfoContext1$inboundSchema),
    z.array(z.lazy(() => InfoContext2$inboundSchema)),
  ]);
/** @internal */
export type Context$Outbound =
  | InfoContext1$Outbound
  | Array<InfoContext2$Outbound>;

/** @internal */
export const Context$outboundSchema: z.ZodType<
  Context$Outbound,
  z.ZodTypeDef,
  Context
> = z.union([
  z.lazy(() => InfoContext1$outboundSchema),
  z.array(z.lazy(() => InfoContext2$outboundSchema)),
]);

export function contextToJSON(context: Context): string {
  return JSON.stringify(Context$outboundSchema.parse(context));
}
export function contextFromJSON(
  jsonString: string,
): SafeParseResult<Context, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Context$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Context' from JSON`,
  );
}

/** @internal */
export const Moderation$inboundSchema: z.ZodType<
  Moderation,
  z.ZodTypeDef,
  unknown
> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "updated_at": "updatedAt",
  });
});
/** @internal */
export type Moderation$Outbound = {
  kind?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
};

/** @internal */
export const Moderation$outboundSchema: z.ZodType<
  Moderation$Outbound,
  z.ZodTypeDef,
  Moderation
> = z.object({
  kind: z.string().optional(),
  status: z.string().optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
}).transform((v) => {
  return remap$(v, {
    updatedAt: "updated_at",
  });
});

export function moderationToJSON(moderation: Moderation): string {
  return JSON.stringify(Moderation$outboundSchema.parse(moderation));
}
export function moderationFromJSON(
  jsonString: string,
): SafeParseResult<Moderation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Moderation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Moderation' from JSON`,
  );
}

/** @internal */
export const RelatedAsset$inboundSchema: z.ZodType<
  RelatedAsset,
  z.ZodTypeDef,
  unknown
> = z.object({});
/** @internal */
export type RelatedAsset$Outbound = {};

/** @internal */
export const RelatedAsset$outboundSchema: z.ZodType<
  RelatedAsset$Outbound,
  z.ZodTypeDef,
  RelatedAsset
> = z.object({});

export function relatedAssetToJSON(relatedAsset: RelatedAsset): string {
  return JSON.stringify(RelatedAsset$outboundSchema.parse(relatedAsset));
}
export function relatedAssetFromJSON(
  jsonString: string,
): SafeParseResult<RelatedAsset, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RelatedAsset$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RelatedAsset' from JSON`,
  );
}

/** @internal */
export const Derivative$inboundSchema: z.ZodType<
  Derivative,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  transformation: z.string().optional(),
  transformation_signature: z.string().optional(),
  secure_url: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "transformation_signature": "transformationSignature",
    "secure_url": "secureUrl",
  });
});
/** @internal */
export type Derivative$Outbound = {
  id?: string | undefined;
  transformation?: string | undefined;
  transformation_signature?: string | undefined;
  secure_url?: string | undefined;
};

/** @internal */
export const Derivative$outboundSchema: z.ZodType<
  Derivative$Outbound,
  z.ZodTypeDef,
  Derivative
> = z.object({
  id: z.string().optional(),
  transformation: z.string().optional(),
  transformationSignature: z.string().optional(),
  secureUrl: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    transformationSignature: "transformation_signature",
    secureUrl: "secure_url",
  });
});

export function derivativeToJSON(derivative: Derivative): string {
  return JSON.stringify(Derivative$outboundSchema.parse(derivative));
}
export function derivativeFromJSON(
  jsonString: string,
): SafeParseResult<Derivative, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Derivative$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Derivative' from JSON`,
  );
}

/** @internal */
export const Info$inboundSchema: z.ZodType<Info, z.ZodTypeDef, unknown> = z
  .object({
    asset_id: z.string().optional(),
    public_id: z.string().optional(),
    asset_folder: z.string().optional(),
    display_name: z.string().optional(),
    folder: z.string().optional(),
    filename: z.string().optional(),
    format: z.string().optional(),
    version: z.number().int().optional(),
    resource_type: z.string().optional(),
    type: z.string().optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    uploaded_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    bytes: z.number().int().optional(),
    backup_bytes: z.number().int().optional(),
    width: z.nullable(z.number().int()).optional(),
    height: z.nullable(z.number().int()).optional(),
    aspect_ratio: z.nullable(z.number()).optional(),
    pixels: z.nullable(z.number().int()).optional(),
    tags: z.nullable(z.array(z.string())).optional(),
    context: z.nullable(
      z.union([
        z.lazy(() => InfoContext1$inboundSchema),
        z.array(z.lazy(() => InfoContext2$inboundSchema)),
      ]),
    ).optional(),
    metadata: z.record(z.any()).optional(),
    moderation_kind: z.string().optional(),
    moderation_status: z.string().optional(),
    moderation: z.array(z.lazy(() => Moderation$inboundSchema)).optional(),
    backup: z.boolean().optional(),
    url: z.string().optional(),
    secure_url: z.string().optional(),
    status: z.string().optional(),
    access_control: z.nullable(z.array(AccessControlItem$inboundSchema))
      .optional(),
    etag: z.string().optional(),
    animated: z.nullable(z.boolean()).optional(),
    duration: z.nullable(z.number()).optional(),
    resource_subtype: z.nullable(z.string()).optional(),
    substatus: z.nullable(z.string()).optional(),
    related_assets: z.nullable(
      z.array(z.lazy(() => RelatedAsset$inboundSchema)),
    ).optional(),
    derivatives: z.nullable(z.array(z.lazy(() => Derivative$inboundSchema)))
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      "asset_id": "assetId",
      "public_id": "publicId",
      "asset_folder": "assetFolder",
      "display_name": "displayName",
      "resource_type": "resourceType",
      "created_at": "createdAt",
      "uploaded_at": "uploadedAt",
      "backup_bytes": "backupBytes",
      "aspect_ratio": "aspectRatio",
      "moderation_kind": "moderationKind",
      "moderation_status": "moderationStatus",
      "secure_url": "secureUrl",
      "access_control": "accessControl",
      "resource_subtype": "resourceSubtype",
      "related_assets": "relatedAssets",
    });
  });
/** @internal */
export type Info$Outbound = {
  asset_id?: string | undefined;
  public_id?: string | undefined;
  asset_folder?: string | undefined;
  display_name?: string | undefined;
  folder?: string | undefined;
  filename?: string | undefined;
  format?: string | undefined;
  version?: number | undefined;
  resource_type?: string | undefined;
  type?: string | undefined;
  created_at?: string | undefined;
  uploaded_at?: string | undefined;
  bytes?: number | undefined;
  backup_bytes?: number | undefined;
  width?: number | null | undefined;
  height?: number | null | undefined;
  aspect_ratio?: number | null | undefined;
  pixels?: number | null | undefined;
  tags?: Array<string> | null | undefined;
  context?:
    | InfoContext1$Outbound
    | Array<InfoContext2$Outbound>
    | null
    | undefined;
  metadata?: { [k: string]: any } | undefined;
  moderation_kind?: string | undefined;
  moderation_status?: string | undefined;
  moderation?: Array<Moderation$Outbound> | undefined;
  backup?: boolean | undefined;
  url?: string | undefined;
  secure_url?: string | undefined;
  status?: string | undefined;
  access_control?: Array<AccessControlItem$Outbound> | null | undefined;
  etag?: string | undefined;
  animated?: boolean | null | undefined;
  duration?: number | null | undefined;
  resource_subtype?: string | null | undefined;
  substatus?: string | null | undefined;
  related_assets?: Array<RelatedAsset$Outbound> | null | undefined;
  derivatives?: Array<Derivative$Outbound> | null | undefined;
};

/** @internal */
export const Info$outboundSchema: z.ZodType<Info$Outbound, z.ZodTypeDef, Info> =
  z.object({
    assetId: z.string().optional(),
    publicId: z.string().optional(),
    assetFolder: z.string().optional(),
    displayName: z.string().optional(),
    folder: z.string().optional(),
    filename: z.string().optional(),
    format: z.string().optional(),
    version: z.number().int().optional(),
    resourceType: z.string().optional(),
    type: z.string().optional(),
    createdAt: z.date().transform(v => v.toISOString()).optional(),
    uploadedAt: z.date().transform(v => v.toISOString()).optional(),
    bytes: z.number().int().optional(),
    backupBytes: z.number().int().optional(),
    width: z.nullable(z.number().int()).optional(),
    height: z.nullable(z.number().int()).optional(),
    aspectRatio: z.nullable(z.number()).optional(),
    pixels: z.nullable(z.number().int()).optional(),
    tags: z.nullable(z.array(z.string())).optional(),
    context: z.nullable(
      z.union([
        z.lazy(() => InfoContext1$outboundSchema),
        z.array(z.lazy(() => InfoContext2$outboundSchema)),
      ]),
    ).optional(),
    metadata: z.record(z.any()).optional(),
    moderationKind: z.string().optional(),
    moderationStatus: z.string().optional(),
    moderation: z.array(z.lazy(() => Moderation$outboundSchema)).optional(),
    backup: z.boolean().optional(),
    url: z.string().optional(),
    secureUrl: z.string().optional(),
    status: z.string().optional(),
    accessControl: z.nullable(z.array(AccessControlItem$outboundSchema))
      .optional(),
    etag: z.string().optional(),
    animated: z.nullable(z.boolean()).optional(),
    duration: z.nullable(z.number()).optional(),
    resourceSubtype: z.nullable(z.string()).optional(),
    substatus: z.nullable(z.string()).optional(),
    relatedAssets: z.nullable(
      z.array(z.lazy(() => RelatedAsset$outboundSchema)),
    ).optional(),
    derivatives: z.nullable(z.array(z.lazy(() => Derivative$outboundSchema)))
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      assetId: "asset_id",
      publicId: "public_id",
      assetFolder: "asset_folder",
      displayName: "display_name",
      resourceType: "resource_type",
      createdAt: "created_at",
      uploadedAt: "uploaded_at",
      backupBytes: "backup_bytes",
      aspectRatio: "aspect_ratio",
      moderationKind: "moderation_kind",
      moderationStatus: "moderation_status",
      secureUrl: "secure_url",
      accessControl: "access_control",
      resourceSubtype: "resource_subtype",
      relatedAssets: "related_assets",
    });
  });

export function infoToJSON(info: Info): string {
  return JSON.stringify(Info$outboundSchema.parse(info));
}
export function infoFromJSON(
  jsonString: string,
): SafeParseResult<Info, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Info$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Info' from JSON`,
  );
}
