/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The delivery type for filtering resources in list operations.
 */
export const ListStorageType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
  Fetch: "fetch",
  List: "list",
} as const;
/**
 * The delivery type for filtering resources in list operations.
 */
export type ListStorageType = ClosedEnum<typeof ListStorageType>;

/** @internal */
export const ListStorageType$inboundSchema: z.ZodNativeEnum<
  typeof ListStorageType
> = z.nativeEnum(ListStorageType);
/** @internal */
export const ListStorageType$outboundSchema: z.ZodNativeEnum<
  typeof ListStorageType
> = ListStorageType$inboundSchema;
