/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The sort direction for the results. Default is "desc".
 */
export const ParametersDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The sort direction for the results. Default is "desc".
 */
export type ParametersDirection = ClosedEnum<typeof ParametersDirection>;

/** @internal */
export const ParametersDirection$inboundSchema: z.ZodNativeEnum<
  typeof ParametersDirection
> = z.nativeEnum(ParametersDirection);
/** @internal */
export const ParametersDirection$outboundSchema: z.ZodNativeEnum<
  typeof ParametersDirection
> = ParametersDirection$inboundSchema;
