/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const SearchSortPair = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SearchSortPair = ClosedEnum<typeof SearchSortPair>;

/** @internal */
export const SearchSortPair$inboundSchema: z.ZodNativeEnum<
  typeof SearchSortPair
> = z.nativeEnum(SearchSortPair);
/** @internal */
export const SearchSortPair$outboundSchema: z.ZodNativeEnum<
  typeof SearchSortPair
> = SearchSortPair$inboundSchema;
