/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The storage type of the resource.
 */
export const StorageType = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
} as const;
/**
 * The storage type of the resource.
 */
export type StorageType = ClosedEnum<typeof StorageType>;

/** @internal */
export const StorageType$inboundSchema: z.ZodNativeEnum<typeof StorageType> = z
  .nativeEnum(StorageType);
/** @internal */
export const StorageType$outboundSchema: z.ZodNativeEnum<typeof StorageType> =
  StorageType$inboundSchema;
