/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The storage type of the resource.
 */
export const StorageTypeParameter = {
  Upload: "upload",
  Private: "private",
  Authenticated: "authenticated",
} as const;
/**
 * The storage type of the resource.
 */
export type StorageTypeParameter = ClosedEnum<typeof StorageTypeParameter>;

/** @internal */
export const StorageTypeParameter$inboundSchema: z.ZodNativeEnum<
  typeof StorageTypeParameter
> = z.nativeEnum(StorageTypeParameter);
/** @internal */
export const StorageTypeParameter$outboundSchema: z.ZodNativeEnum<
  typeof StorageTypeParameter
> = StorageTypeParameter$inboundSchema;
